config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :pictures, only:[:index, :new, :create, :edit, :update, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root 'top#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
      if user && user.admin?
        can :access, :rails_admin
        can :manage, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true, length: { in: 1..140 }
  validates :image, presence: true

  belongs_to :user
  mount_uploader :image, ImageUploader

  def self.pictures_delete(user_id)
    pictures = Picture.where(user_id: user_id)
    unless pictures.blank?
      pictures.delete_all
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable
  mount_uploader :avatar, AvatarUploader
  has_many :pictures

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.extra.raw_info.name,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          image_url:   auth.info.image,
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate: false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource = nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
          name:     auth.info.nickname,
          image_url: auth.info.image,
          provider: auth.provider,
          uid:      auth.uid,
          email:    auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
          password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  PERMISSIBLE_ATTRIBUTES = %i(name avatar avatar_cache)

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: PERMISSIBLE_ATTRIBUTES)
      devise_parameter_sanitizer.permit(:account_update, keys: PERMISSIBLE_ATTRIBUTES)
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only:[:edit, :update, :destroy]
  before_action :authenticate_user!


  def new
    @picture = Picture.new
  end

  def index
    @pictures = Picture.all
  end

  def edit
  end

  def create
    @picture = Picture.create(pictures_params)
    @picture.user_id = current_user.id
    if @picture.save
      redirect_to pictures_path, notice: "写真を投稿しました！"
    else
      render 'new'
    end
  end

  def update
    if @picture.update(pictures_params)
      redirect_to pictures_path, notice: "投稿を更新しました！"
    else
      render 'new'
    end
  end

  def destroy
    @picture.destroy
    redirect_to pictures_path, notice: "投稿を削除しました"
  end

  private
    def pictures_params
      params.require(:picture).permit(:title, :content, :image)
    end

    def set_picture
      @picture = Picture.find(params[:id])
    end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end

  def destroy
    Picture.pictures_delete(current_user.id)
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def profile_img(user)
    return image_tag(user.avatar, alt: user.name) if user.avatar?

    unless user.provider.blank?
      img_url = user.image_url
    else
      img_url = 'no_image.png'
    end
    image_tag(img_url, alt: user.name)
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def photo_img(picture)
    if picture.image?

      image = MiniMagick::Image.open(picture.image.file.file)

      wdth = image[:width]
      hght = image[:height]

      if wdth > 1000 && hght > 500
        image.resize "600x400"
        image.write picture.image.file.file
      end

      image_tag(picture.image, alt: picture.user.name)
    else
      return;
    end
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>なんちゃってInstagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
  <section class="frame-header">
    <header>
      <nav class="navbar navbar-default">
        <div class="container-fuild">
          <div class="navbar-header">
            <%= link_to "トップページ", root_path, class: "navbar-brand" %>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav_target">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse" id="nav_target">
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "投稿一覧", pictures_path %></li>
              <% if user_signed_in? %>
                <li><%= link_to 'マイページ', edit_user_registration_path %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "ログイン", new_user_session_path %></li>
                <li><%= link_to "サインアップ", new_user_registration_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  </section>

<%= yield %>

  <section class="frame-footer">
    <footer>
        <p>なんちゃってInstagram</p>
    </footer>
  </section>

</body>
</html>

app/views/pictures/_form.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(@picture) do |p| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @picture.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= p.label :タイトル  %>
  <%= p.text_field :title, class: 'form-control' %>
  <br>
  <%= p.label :内容 %>
  <%= p.text_field :content, class: 'form-control' %>
  <br>
  <%= p.label :アップロードファイル %>
  <a id="preview"><br><%= photo_img(@picture) %></a>
  <%= p.file_field :image %>

  <br>
  <%= p.submit '投稿', class: 'btn btn-primary btn-block' %>

<% end %>
<%= link_to "投稿一覧に戻る", pictures_path %>

app/views/pictures/edit.html.erb
<div class="container picture-setting">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>投稿編集</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/pictures/index.html.erb
<div class="container">
    <div class="wrapper col-md-12 col-sm-10">
        <div class="col-md-4 col-sm-4 picture-frame-side">
          <p><%= notice %></p>
          <%= link_to "写真を投稿する", new_picture_path, class: 'btn btn-default' %>
        </div>
        <div class="col-md-8 col-sm-12 picture-main">
            <% @pictures.each do |picture| %>
                <div class="picture-frame-main">
                    <p class="img-val">
                      <%= profile_img(picture.user) %>
                    </p>
                    <h4>
                      <strong>
                        <%= picture.title %>
                      </strong>
                    </h4>
                    <p>
                      <%= picture.content %>
                    </p>
                    <p class="img">
                      <%= photo_img(picture) %>
                    </p>
                    <%= link_to "編集", edit_picture_path(picture.id), class: 'btn btn-default btn-sm btn-success' %>
                    <%= link_to "削除", picture_path(picture.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>

                    <p><%= picture.user.name %></p>
                </div>
            <% end %>
            <div id="page-top-btn" class="page-top-btn">
                <p><a class="move-page-top" id="move-page-top">▲</a></p>
            </div>
        </div>
    </div>
</div>

app/views/pictures/new.html.erb
<div class="container picture-setting">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>写真投稿</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/top/index.html.erb
<p id="notice"><%= notice %></p>

<section class="container">
    <div class="row">
        <div class="sm-6">
            <h2>なんちゃってInstagram</h2>
            <p>Instagram風のデモアプリです。</p>
        </div>
    </div>
</section>
<section class="main-header">
    <img src="<%= asset_path "instagram.jpg" %>">
</section>